# Generated by Django 5.2.5 on 2025-09-28 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id_bodega', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('ubicacion', models.CharField(max_length=255)),
                ('capacidad', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id_oc', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('id_usuario', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('id_cliente', models.IntegerField()),
                ('fecha', models.DateField()),
                ('estado', models.CharField(max_length=50)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('unidad', models.CharField(blank=True, max_length=50, null=True)),
                ('precio_base', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('id_receta', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cantidad_producto', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('rut', models.CharField(max_length=30, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('contacto', models.CharField(blank=True, max_length=150, null=True)),
                ('condiciones_comerciales', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('contrasena_hash', models.CharField(max_length=255)),
                ('rol', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id_op', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(max_length=50)),
                ('cantidad_planificada', models.IntegerField()),
                ('cantidad_real', models.IntegerField()),
                ('merma', models.IntegerField()),
                ('id_usuario', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventario.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id_lote', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_vencimiento', models.DateField()),
                ('cantidad_inicial', models.IntegerField()),
                ('cantidad_actual', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventario.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('id_usuario', models.IntegerField()),
                ('updated_at_TIMESTAMP', models.DateTimeField(auto_now=True)),
                ('id_bodega', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventario.bodega')),
                ('id_lote', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventario.lote')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventario.producto')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id_detalle_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.pedido')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventario.producto')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleOC',
            fields=[
                ('id_detalle_oc', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_oc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.ordencompra')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventario.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Costo',
            fields=[
                ('id_costo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventario.producto')),
            ],
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='id_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventario.proveedor'),
        ),
    ]
